# Generated by Django 5.1.4 on 2024-12-19 12:29

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Robot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('model', models.CharField(db_index=True, max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('version', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(2)])),
                ('created', models.DateTimeField()),
            ],
            options={
                'indexes': [models.Index(fields=['model', 'version'], name='robots_robo_model_c98f0b_idx'), models.Index(fields=['created'], name='robots_robo_created_21a443_idx')],
            },
        ),
    ]
